### ISSUE TITLE
Error even though quiz is public

### ISSUE THREAD

**Issue by DiscrimIsPog** [Raymo111/kahoot-answer-bot#10]
I am having this error:

`  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\nodin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiocometd\transports\websocket.py", line 261, in _receive_done
    result = future.result()
asyncio.exceptions.CancelledError
Traceback (most recent call last):
  File "D:\Coding\kahootanswebot\kbot", line 24, in <module>
    user.startGame()
  File "D:\Coding\kahootanswebot\klib.py", line 55, in startGame
    loop.run_until_complete(self._play())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\Coding\kahootanswebot\klib.py", line 99, in _play
    self.answers = await self.findAnswers(quizName, quizAnswers)
  File "D:\Coding\kahootanswebot\klib.py", line 179, in findAnswers
    quizProperties = await self.searchQuiz(name, exceptedAnswers)
  File "D:\Coding\kahootanswebot\klib.py", line 175, in searchQuiz
    raise KahootError("No quiz found. (private?)")
klib.KahootError: No quiz found. (private?)`

**Comment by Raymo111** [comment]
That quiz works for me, what arguments are you passing to kbot?
