### ISSUE TITLE
Pin does not exist error

### ISSUE THREAD

**Issue by 5l1v3r1** [Raymo111/kahoot-answer-bot#3]
Even with the name or quiz id, the script does not work.
For example 
https://kahoot.it/challenge/06036100?challenge-id=11d905ab-fe8e-471c-a069-24bcf77384d1_1609096387623
take a look at this one.
pin is 06036100
and id is 11d905ab-fe8e-471c-a069-24bcf77384d1_1609096387623
the script authenticates successfully but even with the id or the name, everytime it says Pin does not exist.

**Comment by 5l1v3r1** [comment]
In debug mode: output will go brrrrrrrrrrrr
AUTHENTICATED
Traceback (most recent call last):
  File "./kbot", line 100, in <module>
    user.checkPin()
  File "/root/Desktop/kahoot-answer-bot-master/klib.py", line 266, in checkPin
    self.error(f"Pin {self.pin} does not exist.")
  File "/root/Desktop/kahoot-answer-bot-master/klib.py", line 40, in error
    raise KahootError(err)
klib.KahootError: Pin 05248867 does not exist.

**Comment by Raymo111** [comment]
It seems that challenges are a new mode of Kahoots that came out this year. They appear to use a protocol different from regular Kahoots. I'll have to do a bit of WSS reverse engineering. Shouldn't be too much of an issue I don't think.

**Comment by Raymo111** [comment]
Hmm so it seems like Kahoot isn't using WSS at all for the new challenge type. It's using REST. I actually have no idea how to implement the new protocol. You can still use the lookup feature by quizID (everything before the underscore, i.e. `11d905ab-fe8e-471c-a069-24bcf77384d1`). In your specific case it doesn't work because the Kahoot was private.

**Comment by theusaf** [comment]
Just commenting on the previous comment. The id listed in the link is the **challenge** id, which is different from the quiz id. Another interesting thing about challenges is that the entire quiz, even if the quiz is private, is sent through the REST APIs.

**Comment by Raymo111** [comment]
@theusaf interesting. Would you mind taking a shot at it? If you do make a PR and I'll merge it.

**Comment by theusaf** [comment]
I have already implemented challenges in my NodeJS package `kahoot.js-updated`, but I'm working on documenting the API to allow for easy implementation in other languages.
